### ISSUE TITLE
'window is not defined' pre-rendering issue

### ISSUE THREAD

**Issue by barriehadfield** [ruby-hyperloop/hyper-mesh#22]
With a simple Rails 5 app, just after running the generator pre-rendering will not work with a 'window is not defined' V8 error.

I believe this is because react-rails is locked at 1.10.0

The following solves this issue:

```
gem 'react-rails', '1.4.2'
bundle update react-rails
```

Is there a necessary dependency on react-rails 1.10.0?

**Comment by janbiedermann** [comment]
i believe this is gone
