### ISSUE TITLE
Add where and/or enhance find_by

### ISSUE THREAD

**Issue by sfcgeorge** [ruby-hyperloop/hyper-mesh#50]
I was trying to find a join model to delete it, as a workaround for not being able to [delete on a has_many through](https://github.com/ruby-hyperloop/hyper-mesh/issues/49) yet in Hyperloop.
```ruby
PostsTag.find_by(post: post, tag: tag).destroy
```
But this ignores the second attribute (silently) so destroys the wrong record! So then I thought, well a find_by is basically a where so I rewrote
```ruby
PostsTag.where(post: post, tag: tag).first.destroy
```
But there's no where in Hyperloop. So my "solution" was a scope:
```ruby
scope :post_tag, ->(p, t) { where(post_id: p, tag_id: t) }

PostsTag.post_tag(post.id, tag.id).first.destroy
```
But that returns a dummy value instantly so the destroy doesn't work. SO you have to do this:
```ruby
Hyperloop::Model.load do
  PostsTag.post_tag(post.id, tag.id).first
 end.then(&:destroy)
```

**Comment by catmando** [comment]
find_by with multiple attributes now works ab8637bc2b3a250f1e74544245375cb9806a7442
