### ISSUE TITLE
RR object_id changes on execute_remote fetch or save, AKA duplicate objects

### ISSUE THREAD

**Issue by sfcgeorge** [ruby-hyperloop/hyper-mesh#60]
I believe the idea is that all RR records are kept track of by their Opal object_id.

```ruby
r = Record.new
r.object_id #=> 36748

r.save
# { saved_models: [[36750, "Record", ...]] }
```

On save, it seems to add 2 to the object_id, aka it's instantiating an extra object in the save process rather than reusing the one you the programmer created.

On fetch it does the opposite which is doubly weird, the ID of the record being rendered in my code is 2 higher than the ID of the record being fetched. Like every RR instantiation actually instantiates 2 objects, then hyper-mesh uses the wrong one remotely.

Maybe there are 2 datastructures, one for rendering and one for hyper-mesh that aren't sharing objects.

This seems inconsequential, but it's causing me many rendering issues. I have an association rendering a list of components. There's a button to add a new one. I'm using `key` as recommended to ensure order, doing `key: record.object_id`. Adding a record and saving leads to a blank item in the list, or the item disappearing, or sometimes I even get a duplicate saved. I assume due to the above object_id changing and messing up `key` or there being duplicate objects in the RR system.

**Comment by catmando** [comment]
@sfcgeorge is this closed actually?

**Comment by catmando** [comment]
@sfcgeorge is this still an issue?  Im closing, feel free to reopen if you feel its still a problem
